# Generated by Django 3.2 on 2023-01-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artmodel',
            name='year',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
