# Generated by Django 3.2.16 on 2023-01-10 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_anything', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='anythingmodel',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_anything.seasonmodel'),
        ),
    ]
