# Generated by Django 3.2.16 on 2023-01-10 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_anything', '0003_auto_20230110_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anythingmodel',
            old_name='image_name',
            new_name='name',
        ),
    ]
