# Generated by Django 3.2.16 on 2023-01-12 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_anything', '0004_rename_image_name_anythingmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonmodel',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
